// Copyright (c) Privasys. All rights reserved.
// Licensed under the GNU Affero General Public License v3.0.

// Package push sends Expo push notifications and, unlike what it replaces,
// reads what Expo says back.
//
// Four call sites had their own copy of the same twenty lines, and every copy
// ended `resp.Body.Close(); return nil`. The HTTP status was never checked, the
// per-message ticket was never read, and receipts were never fetched. Expo
// returns **HTTP 200 even when an individual message fails**, so a push Expo
// rejected outright was indistinguishable from a delivered one. On 2026-09-07
// pushes stopped for five hours and twelve hours of logs contained nothing at
// all, because there was nothing to write.
//
// Two things follow from Expo's contract, and both were missing:
//
//   - A send returns a TICKET per message. A ticket can be an error even when
//     the HTTP call succeeded, and `DeviceNotRegistered` there means the token
//     is dead and must not be used again.
//   - A ticket later yields a RECEIPT, which is where most delivery failures
//     actually surface. Expo requires consumers to read them and to delete
//     tokens whose receipt is `DeviceNotRegistered`. We never did, so dead
//     tokens accumulated indefinitely: one token is currently registered
//     against three user ids from earlier identities of the same person.
package push

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"time"
)

const (
	sendURL     = "https://exp.host/--/api/v2/push/send"
	receiptsURL = "https://exp.host/--/api/v2/push/getReceipts"

	// Expo's code for a token that will never work again. The only error worth
	// acting on automatically: everything else is transient or ours to fix.
	errDeviceNotRegistered = "DeviceNotRegistered"

	requestTimeout = 10 * time.Second
)

// Message is one notification. The shape every call site was already building
// by hand, with the parts that must not vary (sound, priority) fixed here.
type Message struct {
	Token string
	Title string
	Body  string
	Data  map[string]string
}

// Sender posts to Expo and inspects the answer.
//
// DeadToken, when set, is called with a token Expo has told us is permanently
// unusable, both at ticket time and from a receipt. It is the whole reason the
// receipt sweep exists, so a Sender without one will send fine and prune
// nothing.
type Sender struct {
	Client    *http.Client
	DeadToken func(token string)
}

// Error is a send that Expo refused, carrying the code where there is one so a
// caller (and a log line) can tell a dead token from a bad request.
type Error struct {
	Status  int
	Code    string
	Message string
}

func (e *Error) Error() string {
	if e.Code != "" {
		return fmt.Sprintf("expo push refused (%s): %s", e.Code, e.Message)
	}
	if e.Status != 0 {
		return fmt.Sprintf("expo push refused (HTTP %d): %s", e.Status, e.Message)
	}
	return "expo push refused: " + e.Message
}

// IsDeadToken reports whether err says the token will never work again.
func IsDeadToken(err error) bool {
	e, ok := err.(*Error)
	return ok && e.Code == errDeviceNotRegistered
}

type ticket struct {
	Status  string `json:"status"`
	ID      string `json:"id"`
	Message string `json:"message"`
	Details struct {
		Error string `json:"error"`
	} `json:"details"`
}

func (s *Sender) client() *http.Client {
	if s.Client != nil {
		return s.Client
	}
	return http.DefaultClient
}

// Send delivers one message and returns its ticket id, which is what a later
// receipt lookup needs. A returned id with a nil error means Expo ACCEPTED the
// message, not that it reached the device: that is what receipts are for.
func (s *Sender) Send(ctx context.Context, m Message) (string, error) {
	payload, err := json.Marshal([]map[string]any{{
		"to":    m.Token,
		"sound": "default",
		// APNs priority 10, not the 5 Expo defaults to.
		//
		// Priority 5 tells iOS to "deliver at a time that takes into account
		// power considerations", so it batches and defers. Approvals were
		// arriving ten to fifteen minutes late, worse on a low battery, which
		// is the signature of exactly that. An approval prompt answers
		// something the holder did seconds ago; late, it is worse than useless,
		// because it trains people to approve prompts they can no longer
		// connect to an action.
		//
		// This is the classification Apple asks for: user-visible, time
		// sensitive, generated by user action. Priority 5 is for silent and
		// background pushes, and none of these are that.
		"priority": "high",
		"title":    m.Title,
		"body":     m.Body,
		"data":     m.Data,
	}})
	if err != nil {
		return "", err
	}

	ctx, cancel := context.WithTimeout(ctx, requestTimeout)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, sendURL, bytes.NewReader(payload))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := s.client().Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(io.LimitReader(resp.Body, 64*1024))

	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return "", &Error{Status: resp.StatusCode, Message: snippet(raw)}
	}

	var out struct {
		Data []ticket `json:"data"`
	}
	if err := json.Unmarshal(raw, &out); err != nil || len(out.Data) == 0 {
		// A 200 we cannot read is still a send we cannot vouch for. Saying so
		// is the entire point of this package.
		return "", &Error{Status: resp.StatusCode, Message: "unreadable ticket: " + snippet(raw)}
	}

	t := out.Data[0]
	if t.Status != "ok" {
		e := &Error{Code: t.Details.Error, Message: t.Message}
		if e.Code == errDeviceNotRegistered {
			s.retire(m.Token)
		}
		return "", e
	}
	return t.ID, nil
}

type receipt struct {
	Status  string `json:"status"`
	Message string `json:"message"`
	Details struct {
		Error string `json:"error"`
	} `json:"details"`
}

// ReceiptResult is one ticket's outcome.
type ReceiptResult struct {
	TicketID string
	// Delivered is true only for an explicit "ok" receipt.
	Delivered bool
	// Pending is true when Expo has no receipt yet. NOT a failure: an absent
	// receipt is indistinguishable from an unknown id, so it means "not yet",
	// never "it was not attempted". Reading it the other way sent one
	// investigation down the wrong path entirely.
	Pending bool
	Err     *Error
}

// Receipts looks up delivery outcomes and retires any token Expo reports as
// permanently unusable. Ticket ids that are still pending come back with
// Pending set so the caller can leave them for the next sweep.
func (s *Sender) Receipts(ctx context.Context, ticketIDs []string, tokenFor map[string]string) ([]ReceiptResult, error) {
	if len(ticketIDs) == 0 {
		return nil, nil
	}
	payload, err := json.Marshal(map[string][]string{"ids": ticketIDs})
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, requestTimeout)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, receiptsURL, bytes.NewReader(payload))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := s.client().Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(io.LimitReader(resp.Body, 256*1024))
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return nil, &Error{Status: resp.StatusCode, Message: snippet(raw)}
	}

	var out struct {
		Data map[string]receipt `json:"data"`
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, &Error{Message: "unreadable receipts: " + snippet(raw)}
	}

	results := make([]ReceiptResult, 0, len(ticketIDs))
	for _, id := range ticketIDs {
		r, present := out.Data[id]
		switch {
		case !present:
			results = append(results, ReceiptResult{TicketID: id, Pending: true})
		case r.Status == "ok":
			results = append(results, ReceiptResult{TicketID: id, Delivered: true})
		default:
			e := &Error{Code: r.Details.Error, Message: r.Message}
			if e.Code == errDeviceNotRegistered {
				s.retire(tokenFor[id])
			}
			results = append(results, ReceiptResult{TicketID: id, Err: e})
		}
	}
	return results, nil
}

func (s *Sender) retire(token string) {
	if token == "" || s.DeadToken == nil {
		return
	}
	log.Printf("[push] retiring a token Expo reports as unregistered")
	s.DeadToken(token)
}

func snippet(b []byte) string {
	const max = 300
	if len(b) > max {
		return string(b[:max])
	}
	return string(b)
}

// --- The surface every call site should use -------------------------------

// Store is the slice of the database this package needs. An interface so the
// package stays testable without one, and so it does not import the store.
type Store interface {
	RecordPushTicket(ticketID, userID, pushToken string) error
	DeletePushToken(pushToken string) error
}

// SweepStore adds what the receipt sweep needs on top of Store.
type SweepStore interface {
	Store
	DuePushTickets(minAge time.Duration, limit int) ([]PushTicket, error)
	DeletePushTickets(ticketIDs []string) error
}

// PushTicket mirrors store.PushTicket so this package need not import it.
type PushTicket struct {
	TicketID  string
	UserID    string
	PushToken string
}

// For returns a Sender that retires dead tokens against db.
func For(db Store) *Sender {
	return &Sender{DeadToken: func(token string) {
		if err := db.DeletePushToken(token); err != nil {
			log.Printf("[push] retiring token: %v", err)
		}
	}}
}

// Notify sends one message and records its ticket for the receipt sweep.
//
// This is the whole public surface for a call site: one line, with the status
// check, the ticket inspection and the dead-token retirement behind it. The
// four hand-rolled copies this replaces each did none of those things.
//
// An error here means Expo REFUSED the message and it will never arrive, so it
// is worth logging or surfacing. A nil error means Expo accepted it, which is
// not the same as delivered; that answer comes from the sweep.
func Notify(ctx context.Context, db Store, userID string, m Message) error {
	s := For(db)
	ticketID, err := s.Send(ctx, m)
	if err != nil {
		return err
	}
	if err := db.RecordPushTicket(ticketID, userID, m.Token); err != nil {
		// The push went out; only the follow-up is lost. Not worth failing the
		// caller's request over.
		log.Printf("[push] recording ticket %s: %v", ticketID, err)
	}
	return nil
}

// SweepReceipts reads the receipts for tickets old enough to have one, retires
// any token Expo reports as dead, and clears the rows it has answers for.
//
// Called on a timer. Pending tickets are deliberately left in place: an absent
// receipt means "not yet", not "not attempted".
func SweepReceipts(ctx context.Context, db SweepStore) {
	const (
		minAge = 2 * time.Minute
		batch  = 200
	)
	tickets, err := db.DuePushTickets(minAge, batch)
	if err != nil {
		log.Printf("[push] listing due tickets: %v", err)
		return
	}
	if len(tickets) == 0 {
		return
	}

	ids := make([]string, 0, len(tickets))
	tokenFor := make(map[string]string, len(tickets))
	for _, t := range tickets {
		ids = append(ids, t.TicketID)
		tokenFor[t.TicketID] = t.PushToken
	}

	s := For(db)
	results, err := s.Receipts(ctx, ids, tokenFor)
	if err != nil {
		log.Printf("[push] reading receipts: %v", err)
		return
	}

	var done []string
	var failed int
	for _, r := range results {
		if r.Pending {
			continue
		}
		if r.Err != nil {
			failed++
			// The line that was missing on 2026-09-07, when five hours of
			// undelivered pushes produced no log output whatsoever.
			log.Printf("[push] delivery failed for ticket %s: %v", r.TicketID, r.Err)
		}
		done = append(done, r.TicketID)
	}
	if len(done) > 0 {
		if err := db.DeletePushTickets(done); err != nil {
			log.Printf("[push] clearing answered tickets: %v", err)
		}
	}
	if failed > 0 {
		log.Printf("[push] %d of %d receipts reported a failure", failed, len(done))
	}
}
